spring.application.name=project

# Configuración de conexión a MySQL
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/billetera?useUnicode=true&characterEncoding=UTF-8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate/JPA
# "update" actualizará el esquema de la base de datos automáticamente.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Configuración de Jackson (Deserialización JSON)
spring.jackson.mapper.accept-case-insensitive-enums=true

# JWT Configuration
jwt.secret=${JWT_SECRET:estaEsUnaClaveSuperSecretaYDebeSerLargaParaCumplirConHS256estaEsUnaClaveSuperSecretaYDebeSerLargaParaCumplirConHS256}

# Google OAuth2 Client ID
google.client.id=${GOOGLE_CLIENT_ID:951763280836-6cmm4uctdfeekvnnl0p4qk8aue8far4t.apps.googleusercontent.com}
